language: perl
# Ubuntu 12.04.5 LTS - v5.14.2
# Ubuntu 14.04.4 LTS - v5.18.2
# Ubuntu 16.04.1 LTS - v5.22.1
perl:
  - "5.14"
  - "5.18"
  - "5.22"
  - "blead"
sudo: false
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
  allow_failures:
    - perl: blead
before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
  - eval $(curl https://travis-perl.github.io/init) --auto
  - coverage-setup
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
#script:
#  - prove -l -j$(test-jobs) $(test-files)   # parallel testing
after_success:
  - coverage-report
